### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodeshift#127]
Running `npm run ci`

```
$ npm run ci

> nodeshift@0.13.1 ci C:\Users\hf\Desktop\dev\nodeshift
> npm run lint && npm run coveralls


> nodeshift@0.13.1 lint C:\Users\hf\Desktop\dev\nodeshift
> eslint bin/* lib/**/*.js test/**/*.js index.js


C:\Users\hf\Desktop\dev\nodeshift\bin\nodeshift
  11:1  warning  Expected an assignment or function call and instead saw an expression  no-unused-expressions

✖ 1 problem (0 errors, 1 warning)


> nodeshift@0.13.1 coveralls C:\Users\hf\Desktop\dev\nodeshift
> nyc npm test && nyc report --reporter=text-lcov | coveralls


> nodeshift@0.13.1 test C:\Users\hf\Desktop\dev\nodeshift
> NODESHIFT_QUIET=true tape test/*-test.js test/**/*-test.js | tap-spec

'NODESHIFT_QUIET' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Test failed.  See above for more details.
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodeshift@0.13.1 coveralls: `nyc npm test && nyc report --reporter=text-lcov | coveralls`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodeshift@0.13.1 coveralls script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-10T11_25_09_384Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodeshift@0.13.1 ci: `npm run lint && npm run coveralls`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodeshift@0.13.1 ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-10T11_25_09_415Z-debug.log
```

Related to bucharest-gold/entente#179

Deployment error related to https://github.com/bucharest-gold/mean-booster/issues/22
```console
2017-11-13T22:35:55.883Z TRACE ---> Installing application source
2017-11-13T22:35:55.883Z TRACE cp: cannot stat '/tmp/src/./app/model': Permission denied
2017-11-13T22:35:55.884Z TRACE cp: cannot stat '/tmp/src/./app/resources': Permission denied
2017-11-13T22:35:55.885Z TRACE cp: cannot stat '/tmp/src/./app/controllers': Permission denied
2017-11-13T22:35:55.885Z TRACE cp: cannot stat '/tmp/src/./app/static': Permission denied
2017-11-13T22:35:55.886Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
```

**Comment by helio-frota** [comment]
this is not related to nodeshift, closing.

**Comment by helio-frota** [comment]
The **deploy** works using these steps:
https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/bonjour.adoc#basic-project-creation

```console
hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/mean-booster (master)
$ cp ../bonjour/Dockerfile .

hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/mean-booster (master)
$ cat Dockerfile
FROM bucharestgold/centos7-s2i-nodejs:latest
# The parent image uses ONBUILD to add package.json, run npm install and add bonjour.js
# See https://github.com/ryanj/origin-s2i-nodejs/blob/master/nodejs.org/Dockerfile.onbuild#L65

hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/mean-booster (master)
$ /c/Users/hf/Desktop/dev/cmder/bin/oc new-build --binary --name=meanbooster -l app=meanbooster
    * A Docker build using binary input will be created
      * The resulting image will be pushed to image stream "meanbooster:latest"
      * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label app=meanbooster ...
    imagestream "meanbooster" created
    buildconfig "meanbooster" created
--> Success

hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/mean-booster (master)
$ /c/Users/hf/Desktop/dev/cmder/bin/oc start-build meanbooster --from-dir=. --follow
Uploading directory "." as binary input for the build ...
build "meanbooster-1" started
Receiving source from STDIN as archive ...
Step 1 : FROM bucharestgold/centos7-s2i-nodejs:latest
 ---> 3b5c9605fb06
Step 2 : ENV "OPENSHIFT_BUILD_NAME" "meanbooster-1" "OPENSHIFT_BUILD_NAMESPACE" "myproject"
 ---> Running in d28e8563d76d
 ---> 9a3e75fdfe1b
Removing intermediate container d28e8563d76d
Step 3 : LABEL "io.openshift.build.name" "meanbooster-1" "io.openshift.build.namespace" "myproject"
 ---> Running in b26fb300abfd
 ---> 730a84177bfb
Removing intermediate container b26fb300abfd
Successfully built 730a84177bfb

Pushing image 172.30.1.1:5000/myproject/meanbooster:latest ...
Pushed 0/7 layers, 29% complete
Pushed 1/7 layers, 17% complete
Pushed 2/7 layers, 30% complete
Pushed 3/7 layers, 44% complete
Pushed 4/7 layers, 58% complete
Pushed 5/7 layers, 81% complete
Pushed 6/7 layers, 97% complete
Pushed 7/7 layers, 100% complete
Push successful

hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/mean-booster (master)
$ /c/Users/hf/Desktop/dev/cmder/bin/oc new-app meanbooster -l app=meanbooster
--> Found image 730a841 (4 minutes old) in image stream "myproject/meanbooster" under tag "latest" for "meanbooster"

    Node.js 9.1.0
    -------------
    Platform for building and running Node.js applications

    Tags: builder, nodejs, nodejs-9.1.0

    * This image will be deployed in deployment config "meanbooster"
    * Port 8080/tcp will be load balanced by service "meanbooster"
      * Other containers can access this service through the hostname "meanbooster"

--> Creating resources with label app=meanbooster ...
    deploymentconfig "meanbooster" created
    service "meanbooster" created
--> Success
    Run 'oc status' to view your app.

hf@DESKTOP-137Q3FQ MINGW64 ~/Desktop/dev/mean-booster (master)
```

The app is **not running**, I'm facing the same as: https://github.com/openshift/origin/issues/15176#issuecomment-338439388

**Comment by helio-frota** [comment]
This happen on this phase:
https://github.com/bucharest-gold/centos7-s2i-nodejs/blob/master/s2i/assemble#L21-L22
But, I don't understand why works fine using `oc` command.

**Comment by helio-frota** [comment]
I was using `docker toolbox` + `minishift`.
The same happened with `docker for windows` and `oc cluster up`:

```console
2017-11-16T19:21:44.792Z INFO uploading binary archive C:\Users\hf\Desktop\dev\mean-booster/tmp/nodeshift/build/archive.tar
2017-11-16T19:24:10.309Z INFO binary upload complete
2017-11-16T19:24:10.310Z INFO waiting for build to finish
2017-11-16T19:24:10.334Z TRACE Receiving source from STDIN as archive ...
2017-11-16T19:24:10.335Z TRACE ---> Installing application source
2017-11-16T19:24:10.335Z TRACE cp: cannot stat '/tmp/src/./app/resources': Permission denied
2017-11-16T19:24:10.336Z TRACE cp: cannot stat '/tmp/src/./app/static': Permission denied
2017-11-16T19:24:10.336Z TRACE cp: cannot stat '/tmp/src/./app/controllers': Permission denied
2017-11-16T19:24:10.336Z TRACE cp: cannot stat '/tmp/src/./app/model': Permission denied
2017-11-16T19:24:10.337Z TRACE error: build error: non-zero (13) exit code from bucharestgold/centos7-s2i-nodejs:latest
2017-11-16T19:24:10.597Z ERROR build failed with message: Assemble script failed.
2017-11-16T19:24:10.598Z ERROR Error: Assemble script failed. Error: Assemble script failed.
    at module.exports (C:\Users\hf\Desktop\dev\nodeshift\lib\binary-build.js:40:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mean-booster@1.0.0 openshift: `nodeshift --osc.strictSSL=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean-booster@1.0.0 openshift script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hf\AppData\Roaming\npm-cache\_logs\2017-11-16T19_24_10_627Z-debug.log
```

**Comment by helio-frota** [comment]
Using the latest version of docker-ce for windows and the latest version of `oc`:
I think is good to close this issue for now and try again some day later

![capture](https://user-images.githubusercontent.com/6443576/32949834-fa1109cc-cb82-11e7-86b9-aafb23b4f301.PNG)
![capture2](https://user-images.githubusercontent.com/6443576/32949837-fa2cd2c4-cb82-11e7-9a3d-0f9150d587f5.PNG)

**Comment by gbraad** [comment]
@helio-frota tahnks for the feedback. I notice you run v3.7.0rc.0 and edge. Will try to find out what causes this... (as I also often test with docker for Windows and `oc cluster up`).

**Comment by helio-frota** [comment]
@gbraad thanks!

**Comment by gbraad** [comment]
@helio-frota have you reported this upstream to github.com/openshift/origin against `cluster up`?

**Comment by helio-frota** [comment]
@gbraad not yet

**Comment by gbraad** [comment]
I think this is related to namespace support, and somehow the newer releases of Docker might have an issue or restriction here.

**Comment by gbraad** [comment]
Are you running with "Enable Linux Containers on Windows"?
![image_7702d8a0-6b78-449d-9b7b-cf9a34b080c3](https://user-images.githubusercontent.com/1894/33237160-be856ed6-d2a6-11e7-9caf-77d406038874.png)

**Comment by gbraad** [comment]
@helio-frota Reported as: https://github.com/openshift/origin/issues/17461

**Comment by helio-frota** [comment]
yes, I'm running with "Enable Linux Containers on Windows" (LCOW)
![capture](https://user-images.githubusercontent.com/6443576/33281734-06c87146-d385-11e7-9765-381e741f0949.PNG)

[sorry the feedback delay btw]
