### ISSUE TITLE
getting an unexpected error 

### ISSUE THREAD

**Issue by helio-frota** [bucharest-gold/nodeshift#163]
context:

I made a small change on express code:
```diff
 app.use((req, res, next) => {
-  res.setHeader('Access-Control-Allow-Origin', 'http://localhost:4200');
+  res.setHeader('Access-Control-Allow-Origin', '*');
```

Then when trying to deploy the app again I saw the error:

```
18:44 $ npm run openshift

> mean-booster-backend@0.0.1 openshift /home/hf/Desktop/mea5n-booster/backend
> nodeshift --strictSSL=false --nodeVersion=8.x

2018-01-02T21:44:43.717Z INFO loading configuration
2018-01-02T21:44:43.739Z INFO using namespace myproject at https://192.168.42.194:8443
2018-01-02T21:44:43.749Z INFO creating archive of package.json, model, server.js
2018-01-02T21:44:43.781Z ERROR Error: self signed certificate in certificate chain Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1042:34)
    at TLSSocket.emit (events.js:159:13)
    at TLSSocket._finishInit (_tls_wrap.js:639:8)
```

I logged out on minishift, stop, start, reboot and start and I keep seeing error

**Comment by helio-frota** [comment]
not a bug!
updating to 1.0.0 solves the issue.
